baseURL = "https://fjt7tdmi.github.io/"
languageCode = "ja-JP"
title = "Akifumi Fujita"
theme = "soho"

[params]
author = "Akifumi Fujita"
description = "Portfolio"
copyright = "Akifumi Fujita"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/fjt7tdmi"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/fjt7tdmi/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/fjt7tdmi"
