baseURL = "https://fjt7tdmi.github.io/"
languageCode = "ja-JP"
title = "Akifumi Fujita"
theme = "soho"

summarylength = 10
enableEmoji = true

[params]
author = "Akifumi Fujita"
description = "A system programmer, loves CPU."
copyright = "Akifumi Fujita"
mainSections = ["posts"]
profilePicture = "images/profile.jpg"

    [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/fjt7tdmi"

    [[params.socialIcons]]
    icon = "fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/fjt7tdmi/"

    [[params.socialIcons]]
    icon = "fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/fjt7tdmi"

[menu]
    [[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 300
    url = "/portfolio/"